---
- name: create system groups
  group:
    name: '{{ item.1 }}'
  with_subelements:
    - '{{ users }}'
    - groups
    - flags:
      skip_missing: true
- name: create system users
  user:
    name: '{{ item.name }}'
    shell: /bin/bash
    password: '{{ item.password|default(omit) }}'
    groups: '{{ item.groups|join('','') if item.groups is defined else item.groups|default(omit) }}'
  with_items: '{{ users }}'
