---
- name: create system groups
  group:
    name: '{{ item }}'
  with_items: '{{ lookup(''flattened'', users|map(attribute=''groups''))|list|unique }}'
- name: create system users
  user:
    name: '{{ item.name }}'
    shell: /bin/bash
    password: '{{ item.password|default(omit) }}'
    groups: '{{ item.groups|join('','')|default(omit) }}'
  with_items: '{{ users }}'
