---
- name: install RedHat dependencies
  dnf:
    name: libselinux-python
  when: ansible_os_family == 'RedHat'

- include: linux.yml
  when: ansible_os_family == 'Debian' or
      ansible_os_family == 'RedHat'
- include: openbsd.yml
  when: ansible_distribution == 'OpenBSD'

- name: add authorized keys
  authorized_key:
    key: '{{ item.1 }}'
    user: '{{ item.0.name }}'
  with_subelements:
    - '{{ users }}'
    - ssh_keys
